import PDFDocument from 'pdfkit';

const BRAND = '#840038';
const INK = '#1c1917';
const MUTED = '#78716c';
const RULE = '#e7e5e4';

const PAGE_MARGIN = 50;
const PAGE_WIDTH = 612; // US Letter, points
const PAGE_HEIGHT = 792;
const CONTENT_BOTTOM = PAGE_HEIGHT - PAGE_MARGIN;

/** Render a PDFDocument into a Buffer once the document is finished. */
function toBuffer(doc) {
  return new Promise((resolve, reject) => {
    const chunks = [];
    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);
    doc.end();
  });
}

function kes(amount) {
  return `KES ${Number(amount || 0).toLocaleString('en-KE', { maximumFractionDigits: 2 })}`;
}

function drawHeader(doc, { badge, title, accentColor = BRAND }) {
  doc.rect(0, 0, PAGE_WIDTH, 90).fill('#1c1917');

  doc.fillColor('#ffffff').font('Helvetica-Bold').fontSize(18).text('HAPPY HOUR!', PAGE_MARGIN, 30);
  doc.fillColor('#d6d3d1').font('Helvetica').fontSize(9).text('B2B WHOLESALE TRADE PORTAL', PAGE_MARGIN, 52);
  doc
    .fillColor(accentColor)
    .font('Helvetica-Bold')
    .fontSize(9)
    .text(badge, PAGE_MARGIN, 35, { align: 'right', width: PAGE_WIDTH - PAGE_MARGIN * 2 });

  doc.fillColor(INK).font('Helvetica-Bold').fontSize(14).text(title, PAGE_MARGIN, 110);
}

/** A stack of label/value fields in one column. Returns the y position after the last field. */
function drawFieldColumn(doc, x, y, width, fields) {
  let curY = y;
  fields.forEach(({ label, value, bold }) => {
    doc.fillColor(MUTED).font('Helvetica').fontSize(7.5).text(label.toUpperCase(), x, curY, { width });
    curY += 10;
    doc.fillColor(INK).font(bold ? 'Helvetica-Bold' : 'Helvetica').fontSize(9.5);
    const text = String(value ?? '');
    doc.text(text, x, curY, { width });
    curY += doc.heightOfString(text, { width }) + 9;
  });
  return curY;
}

/** Two side-by-side field columns. Returns the y position below whichever column ran longer. */
function drawTwoColumn(doc, y, left, right) {
  const colWidth = (PAGE_WIDTH - PAGE_MARGIN * 2 - 30) / 2;
  const endLeft = drawFieldColumn(doc, PAGE_MARGIN, y, colWidth, left);
  const endRight = drawFieldColumn(doc, PAGE_MARGIN + colWidth + 30, y, colWidth, right);
  return Math.max(endLeft, endRight) + 6;
}

function drawTableHeader(doc, y, columns) {
  doc.rect(PAGE_MARGIN, y, PAGE_WIDTH - PAGE_MARGIN * 2, 20).fill('#f5f5f4');
  doc.fillColor(MUTED).font('Helvetica-Bold').fontSize(8);
  columns.forEach((col) => {
    doc.text(col.label.toUpperCase(), col.x, y + 6, { width: col.width, align: col.align || 'left' });
  });
  return y + 26;
}

/** One data row. Wraps and returns the y position below it, accounting for the tallest cell. */
function drawTableRow(doc, y, columns, row) {
  doc.fillColor(INK).font('Helvetica').fontSize(9);
  let maxHeight = 14;
  columns.forEach((col) => {
    const text = String(col.value(row) ?? '');
    maxHeight = Math.max(maxHeight, doc.heightOfString(text, { width: col.width }));
  });
  columns.forEach((col) => {
    doc.text(String(col.value(row) ?? ''), col.x, y, { width: col.width, align: col.align || 'left' });
  });
  const bottom = y + maxHeight + 8;
  doc.moveTo(PAGE_MARGIN, bottom).lineTo(PAGE_WIDTH - PAGE_MARGIN, bottom).strokeColor(RULE).lineWidth(0.5).stroke();
  return bottom + 6;
}

/** Advance past a table row, starting a fresh page (with a repeated header) if it would overflow. */
function ensureRoom(doc, y, needed, columns, redrawHeader) {
  if (y + needed <= CONTENT_BOTTOM) return y;
  doc.addPage({ size: 'LETTER', margin: PAGE_MARGIN });
  return redrawHeader ? drawTableHeader(doc, PAGE_MARGIN, columns) : PAGE_MARGIN;
}

/** Render a KRA VAT tax invoice (as generated by generateTradeInvoiceDocument) to a PDF Buffer. */
export async function renderInvoicePdf(invoice) {
  const doc = new PDFDocument({ size: 'LETTER', margin: PAGE_MARGIN, bufferPages: true });

  drawHeader(doc, { badge: 'OFFICIAL KRA VAT TAX INVOICE', title: `Invoice ${invoice.invoiceNumber}` });

  let y = drawTwoColumn(
    doc,
    145,
    [
      { label: 'Order', value: invoice.orderNumber, bold: true },
      { label: 'Issue Date', value: invoice.issueDate },
      { label: 'Due Date', value: invoice.dueDate, bold: true },
      { label: 'ETR Control No.', value: invoice.etrControlNumber || 'N/A' },
    ],
    [
      { label: 'Bill To', value: invoice.customer.legalName, bold: true },
      { label: 'Trading As', value: invoice.customer.tradingName },
      { label: 'KRA PIN', value: invoice.customer.kraPin },
      { label: 'PO Reference', value: invoice.poReference || 'N/A' },
    ]
  );

  const columns = [
    { label: 'Item', x: PAGE_MARGIN, width: 190 },
    { label: 'Qty', x: PAGE_MARGIN + 195, width: 40, align: 'center' },
    { label: 'Unit (Inc-VAT)', x: PAGE_MARGIN + 240, width: 100, align: 'right' },
    { label: 'Total (KES)', x: PAGE_MARGIN + 345, width: 105, align: 'right' },
  ];
  const rowColumns = [
    { ...columns[0], value: (r) => r.name },
    { ...columns[1], value: (r) => r.quantity },
    { ...columns[2], value: (r) => kes(r.unitPriceIncVat) },
    { ...columns[3], value: (r) => kes(r.lineTotalIncVat) },
  ];

  y = drawTableHeader(doc, y + 10, columns);
  for (const item of invoice.items || []) {
    y = ensureRoom(doc, y, 24, columns, true);
    y = drawTableRow(doc, y, rowColumns, item);
  }

  y = ensureRoom(doc, y, 140, columns, false);
  y += 8;

  const totals = [
    ['Goods Subtotal (Ex-VAT)', kes(invoice.subtotalExVat)],
    ['Kenya VAT (16%)', kes(invoice.vatTotal)],
    ['Delivery & Handling', invoice.deliveryFee === 0 ? 'FREE' : kes(invoice.deliveryFee)],
  ];
  if (invoice.referralCredit > 0) totals.push(['Referral Credit', `- ${kes(invoice.referralCredit)}`]);

  doc.fontSize(9);
  totals.forEach(([label, value], i) => {
    const rowY = y + i * 15;
    doc.fillColor(MUTED).font('Helvetica').text(label, PAGE_MARGIN + 220, rowY, { width: 125, align: 'right' });
    doc.fillColor(INK).font('Helvetica-Bold').text(value, PAGE_MARGIN + 345, rowY, { width: 105, align: 'right' });
  });
  y += totals.length * 15 + 6;
  doc.moveTo(PAGE_MARGIN + 220, y).lineTo(PAGE_WIDTH - PAGE_MARGIN, y).strokeColor(BRAND).lineWidth(1).stroke();
  y += 8;
  doc.fillColor(BRAND).font('Helvetica-Bold').fontSize(11);
  doc.text('TOTAL AMOUNT DUE', PAGE_MARGIN + 180, y, { width: 165, align: 'right' });
  doc.text(kes(invoice.grandTotal), PAGE_MARGIN + 345, y, { width: 105, align: 'right' });

  y += 36;
  y = ensureRoom(doc, y, 60, columns, false);
  doc.fillColor(INK).font('Helvetica-Bold').fontSize(9).text('Settlement Instructions', PAGE_MARGIN, y);
  y += 14;
  doc.font('Helvetica').fontSize(8).fillColor(MUTED);
  doc.text(`M-Pesa Paybill: ${invoice.paymentInstructions?.paybill || 'N/A'}   Account Ref: ${invoice.invoiceNumber}`, PAGE_MARGIN, y);
  y += 12;
  doc.text(`Bank: ${invoice.paymentInstructions?.bankName || 'N/A'}   Account: ${invoice.paymentInstructions?.accountNumber || 'N/A'} (${invoice.paymentInstructions?.swiftCode || ''})`, PAGE_MARGIN, y);

  const range = doc.bufferedPageRange();
  for (let i = 0; i < range.count; i++) {
    doc.switchToPage(range.start + i);
    doc
      .fillColor(MUTED)
      .fontSize(7)
      .text(
        `${invoice.supplier.companyName} · KRA PIN: ${invoice.supplier.kraPin} · VAT No: ${invoice.supplier.vatNumber} · ${invoice.supplier.physicalAddress}`,
        PAGE_MARGIN,
        CONTENT_BOTTOM - 30,
        { width: PAGE_WIDTH - PAGE_MARGIN * 2, align: 'center' }
      );
  }

  return toBuffer(doc);
}

/** Render a quotation (as generated by generateTradeQuoteDocument) to a PDF Buffer. */
export async function renderQuotePdf(quote) {
  const doc = new PDFDocument({ size: 'LETTER', margin: PAGE_MARGIN, bufferPages: true });

  drawHeader(doc, { badge: 'QUOTATION — NOT A TAX INVOICE', title: `Quote ${quote.quoteNumber}`, accentColor: '#2563eb' });

  let y = drawTwoColumn(
    doc,
    145,
    [
      { label: 'Issue Date', value: quote.issueDate },
      { label: 'Valid Until', value: quote.validUntil || 'N/A', bold: true },
      { label: 'Status', value: (quote.status || 'sent').toUpperCase() },
    ],
    [
      { label: 'Quote For', value: quote.customer.legalName, bold: true },
      { label: 'Trading As', value: quote.customer.tradingName },
      { label: 'KRA PIN', value: quote.customer.kraPin },
    ]
  );

  const columns = [
    { label: 'Item', x: PAGE_MARGIN, width: 190 },
    { label: 'Qty', x: PAGE_MARGIN + 195, width: 40, align: 'center' },
    { label: 'Unit (Inc-VAT)', x: PAGE_MARGIN + 240, width: 100, align: 'right' },
    { label: 'Total (KES)', x: PAGE_MARGIN + 345, width: 105, align: 'right' },
  ];
  const rowColumns = [
    { ...columns[0], value: (r) => r.name },
    { ...columns[1], value: (r) => r.quantity },
    { ...columns[2], value: (r) => kes(r.unitPriceIncVat) },
    { ...columns[3], value: (r) => kes(r.lineTotalIncVat) },
  ];

  y = drawTableHeader(doc, y + 10, columns);
  for (const item of quote.items || []) {
    y = ensureRoom(doc, y, 24, columns, true);
    y = drawTableRow(doc, y, rowColumns, item);
  }

  y = ensureRoom(doc, y, 120, columns, false);
  y += 8;

  const totals = [
    ['Goods Subtotal (Ex-VAT)', kes(quote.subtotalExVat)],
    ['Kenya VAT (16%)', kes(quote.vatTotal)],
    ['Delivery & Handling', quote.deliveryFee === 0 ? 'FREE' : kes(quote.deliveryFee)],
  ];

  doc.fontSize(9);
  totals.forEach(([label, value], i) => {
    const rowY = y + i * 15;
    doc.fillColor(MUTED).font('Helvetica').text(label, PAGE_MARGIN + 220, rowY, { width: 125, align: 'right' });
    doc.fillColor(INK).font('Helvetica-Bold').text(value, PAGE_MARGIN + 345, rowY, { width: 105, align: 'right' });
  });
  y += totals.length * 15 + 6;
  doc.moveTo(PAGE_MARGIN + 220, y).lineTo(PAGE_WIDTH - PAGE_MARGIN, y).strokeColor('#2563eb').lineWidth(1).stroke();
  y += 8;
  doc.fillColor('#2563eb').font('Helvetica-Bold').fontSize(11);
  doc.text('ESTIMATED TOTAL', PAGE_MARGIN + 180, y, { width: 165, align: 'right' });
  doc.text(kes(quote.grandTotal), PAGE_MARGIN + 345, y, { width: 105, align: 'right' });

  if (quote.notes) {
    y += 36;
    y = ensureRoom(doc, y, 40, columns, false);
    doc.fillColor(INK).font('Helvetica-Bold').fontSize(9).text('Notes', PAGE_MARGIN, y);
    y += 12;
    doc.font('Helvetica').fontSize(8).fillColor(MUTED).text(quote.notes, PAGE_MARGIN, y, { width: PAGE_WIDTH - PAGE_MARGIN * 2 });
  }

  const range = doc.bufferedPageRange();
  for (let i = 0; i < range.count; i++) {
    doc.switchToPage(range.start + i);
    doc
      .fillColor(MUTED)
      .fontSize(7)
      .text(
        'This is an estimate only and does not constitute a tax invoice. Prices are subject to stock availability at time of order.',
        PAGE_MARGIN,
        CONTENT_BOTTOM - 20,
        { width: PAGE_WIDTH - PAGE_MARGIN * 2, align: 'center' }
      );
  }

  return toBuffer(doc);
}

/** Render a delivery note / GRN (as generated by generateTradeDeliveryNote) to a PDF Buffer. */
export async function renderDeliveryNotePdf(deliveryNote) {
  const doc = new PDFDocument({ size: 'LETTER', margin: PAGE_MARGIN, bufferPages: true });

  drawHeader(doc, { badge: 'DELIVERY NOTE & GRN', title: `Delivery Note ${deliveryNote.deliveryNoteNumber}`, accentColor: '#059669' });

  let y = drawTwoColumn(
    doc,
    145,
    [
      { label: 'Order', value: deliveryNote.orderNumber, bold: true },
      { label: 'Dispatch Date', value: deliveryNote.dispatchDate },
      { label: 'Security Seal', value: deliveryNote.sealNumber, bold: true },
    ],
    [
      { label: 'Deliver To', value: deliveryNote.customer.tradingName, bold: true },
      { label: 'Address', value: deliveryNote.customer.deliveryAddress?.addressLine || 'N/A' },
      { label: 'Driver', value: `${deliveryNote.logistics.driverName} (${deliveryNote.logistics.vehicleRegistration})` },
    ]
  );

  const columns = [
    { label: 'SKU / Product', x: PAGE_MARGIN, width: 260 },
    { label: 'Ordered', x: PAGE_MARGIN + 265, width: 90, align: 'center' },
    { label: 'Dispatched', x: PAGE_MARGIN + 360, width: 90, align: 'center' },
    { label: 'Received', x: PAGE_MARGIN + 455, width: 70, align: 'center' },
  ];
  const rowColumns = [
    { ...columns[0], value: (r) => `${r.name} (${r.sku})` },
    { ...columns[1], value: (r) => r.orderedQuantity },
    { ...columns[2], value: (r) => r.dispatchedQuantity },
    { ...columns[3], value: (r) => r.receivedQuantity },
  ];

  y = drawTableHeader(doc, y + 10, columns);
  for (const item of deliveryNote.items || []) {
    y = ensureRoom(doc, y, 24, columns, true);
    y = drawTableRow(doc, y, rowColumns, item);
  }

  y = ensureRoom(doc, y, 100, columns, false);
  y += 14;
  doc.fillColor(MUTED).font('Helvetica').fontSize(8).text(deliveryNote.notes || '', PAGE_MARGIN, y, { width: PAGE_WIDTH - PAGE_MARGIN * 2 });
  y += doc.heightOfString(deliveryNote.notes || '', { width: PAGE_WIDTH - PAGE_MARGIN * 2 }) + 50;

  doc.strokeColor(RULE).moveTo(PAGE_MARGIN, y).lineTo(PAGE_MARGIN + 200, y).stroke();
  doc.fillColor(MUTED).fontSize(8).text('Received in good condition — Signature', PAGE_MARGIN, y + 4);
  doc.strokeColor(RULE).moveTo(PAGE_MARGIN + 260, y).lineTo(PAGE_MARGIN + 460, y).stroke();
  doc.text('Date', PAGE_MARGIN + 260, y + 4);

  return toBuffer(doc);
}
