export const CATEGORIES = [
  { id: "fast6", label: "Fast 6", icon: "bolt" },
  { id: "whiskey", label: "Whiskey", icon: null },
  { id: "gin", label: "Gin", icon: null },
  { id: "tequila", label: "Tequila", icon: null },
  { id: "rum", label: "Rum", icon: null },
  { id: "vodka", label: "Vodka", icon: null },
  { id: "cognac", label: "Cognac", icon: null },
  { id: "soju", label: "Soju", icon: null },
  { id: "mixers", label: "Mixers", icon: null },
  { id: "sparkling", label: "Sparkling", icon: null },
  { id: "champagne", label: "Champagne", icon: null },
  { id: "liqueurs", label: "Liqueurs", icon: null },
  { id: "beer", label: "Beer", icon: null },
  { id: "non-alcoholic", label: "Non-Alcoholic", icon: null },
  { id: "cocktails", label: "Cocktails", icon: null },
  { id: "party-packs", label: "Party Packs", icon: null },
];

export const BRANDS = [
  {
    id: "tusker",
    name: "Tusker",
    logo: "https://lh3.googleusercontent.com/aida/AP1WRLtrs1e57xw0yhV0PPxg7E64QC71DPKKb9i3Lgrjn_UHuq26LzS47hhIAGxyHQh0o-F29SfHVG3uYmiHrulIQpuZS3j73CLHGnufiIjDPAdOd6drhkfTN_rZxD5XOCQeKghZu3rtLfS_gFvS0rOk_exE42OBLqiyWrDt4Nr_NyIQFynYiV7hu83-i5dAnGIMLKRUiv0B5Xx67tPgpgKVlfaEIiC7GIzIgR0YeOju5CXZcviI403U2ZC7O7w",
  },
  {
    id: "jameson",
    name: "Jameson",
    logo: "https://lh3.googleusercontent.com/aida/AP1WRLs4o8ENl79dufVxwm_ZaX6DiVsdDIZtyVJtA25AH9sSlK8QF_VH0_eoNOvqAnw09sf42Y7z-3gWT3Q5WeNNumxUcLtYGVspMjYkfyZVzygk8SlqD2mXLF7rEq_u1Hxuol-f2M6uCHi4oNb7n1YqyC3mcVX-DVgs0uO-4z_Hg5vctSPgOQxzGLywqluczJNqFxy0M82lWMMImRB4fGDXr9Fe6btL8NEjsdheMdrYG5aBYg6jR9h7jWCngzY",
  },
  {
    id: "gilbeys",
    name: "Gilbeys",
    logo: "https://lh3.googleusercontent.com/aida/AP1WRLtTNXgPcdoOYhBEBvau1YNJ_R25lFh6l_1gklaQE0wIFJfvhLzGDebNR5s5zovs7zoBQr7kj6Mk-RE3eYUhFDq0dOvWXf-uE4ctW9QpS1o8RKAfP4YkQRYJ2GwYBcmnVg5RSbqpx5FcVIse8ucBQGWkPWpwoIGhdDEDOALkhm3bdRf6aN-CqMDdsxejrmQ8L1BnJnA7EjUh0lQ0qLyqoDgzhmCnyp-2szbC1pnsWYJaJaBq24vrvKg84jY",
  },
  {
    id: "smirnoff",
    name: "Smirnoff",
    logo: "https://lh3.googleusercontent.com/aida/AP1WRLsCn1MRCS1Ljq7PdbBAy-OfUE1frSQzceTdG0iftwK-tWmLZkbxXBw639cbTNs7NpGfpSNAzG9JfKm1hpWbkmKYmmzaBol_zid2_y8rbsGghELE8Nd_cgcAx9WyggSGHyPw4E4ZhKBXg40-wesXB4z-bWR7iStD9ADgGVjus-71Tn7ZK4RSEh5KbNr1EnYx5ZS6ALnfs_YOTlrOm6dawXIqxdC4oMwgNqc6swuM8aTkiB3gotHZLBYt96o",
  },
];

export const PRODUCTS = [
  {
    id: 1,
    name: "Tusker Lager",
    size: "500ml",
    price: 250,
    category: "beer",
    fast6: true,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCvDoUiG7Bibf4hDXgo53IxtDHSaC6ly6KMYJGzVkLr9yRl9TgBjqeSdO5icCz7RqLV5h1rNuzmBr_y8_-MVJ_cBq-MAnNWSCEQC4I-8ivZ4b3MtZuFNO9Xikwljt2qUfZWut5WBwQd1oTfmrrPJIU5H_qShDwRZ5MkUaBoK_K_B-PUb9iRpuhd21A6GCsWjs5jTLIJD4s9fm30p7-udB_20KGGSOKm-rwO1O7s5aKWuAkG65dPdkrC",
  },
  {
    id: 2,
    name: "Jameson Irish Whiskey",
    size: "750ml",
    price: 3200,
    category: "spirits",
    fast6: false,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCzALOLvFjeLjElJNGLIgqtGKw4wptEGO3uE26PCDnuj5mvaO-iMMmSm0-JTrOXK3mlXssc5rpXENtwZVIxuciZ2qlGAqxPtojPnBxS8yjPAUZjDwTpJXtf_aSJD3ENUdFBlemGi9aZY-XLLRVO3JOc38Ew5uS2X41UBTw3IuOwTcK4CmeRtChH63Tj9b7teElKKdDPkxBUMhAtdZ4z6ris_T0ymRHndEJQ8bvw9e3A7wSePHIRmMiM",
  },
  {
    id: 3,
    name: "Bag of Ice",
    size: "2kg",
    price: 150,
    category: "mixers",
    fast6: true,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuBVhbpC-gw_OQK2HjzRPdCdYEe8JdMtMH2hDo7pUzkVRaZhd47LdJoxttW9sOPdadwA3kSbiJYjH_zo4WKCl7z6sGGNuDbGHs2vXyTyi7joGZIcyWcwlEisQyFlzVsyyKuOa2PbtgEAJyEzmdBtX9MExnRTM5mVPT0AnJpcIavRHW1yY5cbIVdONjf8B-K_ySl4FBPXaFjgp-MTrBirAW6lAJCBrilDACrZdp-64xnsvUQDtAeLQK_j",
  },
  {
    id: 4,
    name: "Tonic Water",
    size: "1L",
    price: 200,
    category: "mixers",
    fast6: false,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCRcy3feQvg-WQja0f5WO9bhjfIwFohZeXXBjmKroWAsqH62OZ4eucQ-fWoguJBP5KDnGgzjSaAyGdkhVtPug26uTuWIEw2ZqkFTvGeLKQ9pM4p-hzM_NCaUR4caG2RqrjHJI5O8P7J76iLGK-LUciSTCSygMJtrS547puVLPsmm7ncD9ekQt9YqAnUXE80oVsIKevepNvtubN1Sxtv3XoI1yDT7Dg3FEcjGZozWKpPabYTAaWZh-EJ",
  },
  {
    id: 5,
    name: "Tusker Lager",
    size: "500ml",
    price: 250,
    category: "beer",
    fast6: true,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCvDoUiG7Bibf4hDXgo53IxtDHSaC6ly6KMYJGzVkLr9yRl9TgBjqeSdO5icCz7RqLV5h1rNuzmBr_y8_-MVJ_cBq-MAnNWSCEQC4I-8ivZ4b3MtZuFNO9Xikwljt2qUfZWut5WBwQd1oTfmrrPJIU5H_qShDwRZ5MkUaBoK_K_B-PUb9iRpuhd21A6GCsWjs5jTLIJD4s9fm30p7-udB_20KGGSOKm-rwO1O7s5aKWuAkG65dPdkrC",
  },
  {
    id: 6,
    name: "Gilbeys Vodka",
    size: "750ml",
    price: 1800,
    category: "spirits",
    fast6: false,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCzALOLvFjeLjElJNGLIgqtGKw4wptEGO3uE26PCDnuj5mvaO-iMMmSm0-JTrOXK3mlXssc5rpXENtwZVIxuciZ2qlGAqxPtojPnBxS8yjPAUZjDwTpJXtf_aSJD3ENUdFBlemGi9aZY-XLLRVO3JOc38Ew5uS2X41UBTw3IuOwTcK4CmeRtChH63Tj9b7teElKKdDPkxBUMhAtdZ4z6ris_T0ymRHndEJQ8bvw9e3A7wSePHIRmMiM",
  },
  {
    id: 7,
    name: "Smirnoff Red",
    size: "750ml",
    price: 2200,
    category: "spirits",
    fast6: false,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuBVhbpC-gw_OQK2HjzRPdCdYEe8JdMtMH2hDo7pUzkVRaZhd47LdJoxttW9sOPdadwA3kSbiJYjH_zo4WKCl7z6sGGNuDbGHs2vXyTyi7joGZIcyWcwlEisQyFlzVsyyKuOa2PbtgEAJyEzmdBtX9MExnRTM5mVPT0AnJpcIavRHW1yY5cbIVdONjf8B-K_ySl4FBPXaFjgp-MTrBirAW6lAJCBrilDACrZdp-64xnsvUQDtAeLQK_j",
  },
  {
    id: 8,
    name: "Coca-Cola",
    size: "1L",
    price: 150,
    category: "mixers",
    fast6: true,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCRcy3feQvg-WQja0f5WO9bhjfIwFohZeXXBjmKroWAsqH62OZ4eucQ-fWoguJBP5KDnGgzjSaAyGdkhVtPug26uTuWIEw2ZqkFTvGeLKQ9pM4p-hzM_NCaUR4caG2RqrjHJI5O8P7J76iLGK-LUciSTCSygMJtrS547puVLPsmm7ncD9ekQt9YqAnUXE80oVsIKevepNvtubN1Sxtv3XoI1yDT7Dg3FEcjGZozWKpPabYTAaWZh-EJ",
  },
];

export const NEIGHBORHOODS = [
  "Kilimani",
  "Westlands",
  "Lavington",
  "Karen",
];
