export const CATEGORIES = [
  { id: "fast6", label: "Fast 6", icon: "bolt" },
  { id: "whiskey", label: "Whiskey", icon: null },
  { id: "gin", label: "Gin", icon: null },
  { id: "tequila", label: "Tequila", icon: null },
  { id: "rum", label: "Rum", icon: null },
  { id: "vodka", label: "Vodka", icon: null },
  { id: "cognac", label: "Cognac", icon: null },
  { id: "soju", label: "Soju", icon: null },
  { id: "mixers", label: "Mixers", icon: null },
  { id: "sparkling", label: "Sparkling", icon: null },
  { id: "champagne", label: "Champagne", icon: null },
  { id: "liqueurs", label: "Liqueurs", icon: null },
  { id: "beer", label: "Beer", icon: null },
  { id: "non-alcoholic", label: "Non-Alcoholic", icon: null },
  { id: "cocktails", label: "Cocktails", icon: null },
  { id: "party-packs", label: "Party Packs", icon: null },
];

export const BRANDS = [
  { id: "ballantines", name: "Ballantine’s", logo: "https://myhappyhour.co.ke/wp-content/uploads/2025/03/Group-25.webp" },
  { id: "beefeater", name: "Beefeater", logo: "https://myhappyhour.co.ke/wp-content/uploads/2025/03/Group-26.webp" },
  { id: "belaire", name: "Belaire", logo: "https://myhappyhour.co.ke/wp-content/uploads/2025/03/Group-35.webp" },
  { id: "chivas", name: "Chivas", logo: "https://myhappyhour.co.ke/wp-content/uploads/2025/03/Group-28.webp" },
  { id: "glenlivet", name: "Glenlivet", logo: "https://myhappyhour.co.ke/wp-content/uploads/2025/03/Group-32.webp" },
  { id: "jameson", name: "Jameson", logo: "https://myhappyhour.co.ke/wp-content/uploads/2025/03/Group-31.webp" },
  { id: "jinro", name: "Jinro", logo: "https://myhappyhour.co.ke/wp-content/uploads/2026/07/jinro-logo.webp" },
  { id: "malfy", name: "Malfy", logo: "https://myhappyhour.co.ke/wp-content/uploads/2025/03/Group-30.webp" },
  { id: "martell", name: "Martell", logo: "https://myhappyhour.co.ke/wp-content/uploads/2025/03/Group-29.webp" },
  { id: "olmeca", name: "Olmeca", logo: "https://myhappyhour.co.ke/wp-content/uploads/2025/03/Group-33.webp" },
];

export const PRODUCTS = [
  {
    id: 1,
    name: "Tusker Lager",
    size: "500ml",
    price: 250,
    category: "beer",
    fast6: true,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCvDoUiG7Bibf4hDXgo53IxtDHSaC6ly6KMYJGzVkLr9yRl9TgBjqeSdO5icCz7RqLV5h1rNuzmBr_y8_-MVJ_cBq-MAnNWSCEQC4I-8ivZ4b3MtZuFNO9Xikwljt2qUfZWut5WBwQd1oTfmrrPJIU5H_qShDwRZ5MkUaBoK_K_B-PUb9iRpuhd21A6GCsWjs5jTLIJD4s9fm30p7-udB_20KGGSOKm-rwO1O7s5aKWuAkG65dPdkrC",
  },
  {
    id: 2,
    name: "Jameson Irish Whiskey",
    size: "750ml",
    price: 3200,
    category: "spirits",
    fast6: false,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCzALOLvFjeLjElJNGLIgqtGKw4wptEGO3uE26PCDnuj5mvaO-iMMmSm0-JTrOXK3mlXssc5rpXENtwZVIxuciZ2qlGAqxPtojPnBxS8yjPAUZjDwTpJXtf_aSJD3ENUdFBlemGi9aZY-XLLRVO3JOc38Ew5uS2X41UBTw3IuOwTcK4CmeRtChH63Tj9b7teElKKdDPkxBUMhAtdZ4z6ris_T0ymRHndEJQ8bvw9e3A7wSePHIRmMiM",
  },
  {
    id: 3,
    name: "Bag of Ice",
    size: "2kg",
    price: 150,
    category: "mixers",
    fast6: true,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuBVhbpC-gw_OQK2HjzRPdCdYEe8JdMtMH2hDo7pUzkVRaZhd47LdJoxttW9sOPdadwA3kSbiJYjH_zo4WKCl7z6sGGNuDbGHs2vXyTyi7joGZIcyWcwlEisQyFlzVsyyKuOa2PbtgEAJyEzmdBtX9MExnRTM5mVPT0AnJpcIavRHW1yY5cbIVdONjf8B-K_ySl4FBPXaFjgp-MTrBirAW6lAJCBrilDACrZdp-64xnsvUQDtAeLQK_j",
  },
  {
    id: 4,
    name: "Tonic Water",
    size: "1L",
    price: 200,
    category: "mixers",
    fast6: false,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCRcy3feQvg-WQja0f5WO9bhjfIwFohZeXXBjmKroWAsqH62OZ4eucQ-fWoguJBP5KDnGgzjSaAyGdkhVtPug26uTuWIEw2ZqkFTvGeLKQ9pM4p-hzM_NCaUR4caG2RqrjHJI5O8P7J76iLGK-LUciSTCSygMJtrS547puVLPsmm7ncD9ekQt9YqAnUXE80oVsIKevepNvtubN1Sxtv3XoI1yDT7Dg3FEcjGZozWKpPabYTAaWZh-EJ",
  },
  {
    id: 5,
    name: "Tusker Lager",
    size: "500ml",
    price: 250,
    category: "beer",
    fast6: true,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCvDoUiG7Bibf4hDXgo53IxtDHSaC6ly6KMYJGzVkLr9yRl9TgBjqeSdO5icCz7RqLV5h1rNuzmBr_y8_-MVJ_cBq-MAnNWSCEQC4I-8ivZ4b3MtZuFNO9Xikwljt2qUfZWut5WBwQd1oTfmrrPJIU5H_qShDwRZ5MkUaBoK_K_B-PUb9iRpuhd21A6GCsWjs5jTLIJD4s9fm30p7-udB_20KGGSOKm-rwO1O7s5aKWuAkG65dPdkrC",
  },
  {
    id: 6,
    name: "Gilbeys Vodka",
    size: "750ml",
    price: 1800,
    category: "spirits",
    fast6: false,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCzALOLvFjeLjElJNGLIgqtGKw4wptEGO3uE26PCDnuj5mvaO-iMMmSm0-JTrOXK3mlXssc5rpXENtwZVIxuciZ2qlGAqxPtojPnBxS8yjPAUZjDwTpJXtf_aSJD3ENUdFBlemGi9aZY-XLLRVO3JOc38Ew5uS2X41UBTw3IuOwTcK4CmeRtChH63Tj9b7teElKKdDPkxBUMhAtdZ4z6ris_T0ymRHndEJQ8bvw9e3A7wSePHIRmMiM",
  },
  {
    id: 7,
    name: "Smirnoff Red",
    size: "750ml",
    price: 2200,
    category: "spirits",
    fast6: false,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuBVhbpC-gw_OQK2HjzRPdCdYEe8JdMtMH2hDo7pUzkVRaZhd47LdJoxttW9sOPdadwA3kSbiJYjH_zo4WKCl7z6sGGNuDbGHs2vXyTyi7joGZIcyWcwlEisQyFlzVsyyKuOa2PbtgEAJyEzmdBtX9MExnRTM5mVPT0AnJpcIavRHW1yY5cbIVdONjf8B-K_ySl4FBPXaFjgp-MTrBirAW6lAJCBrilDACrZdp-64xnsvUQDtAeLQK_j",
  },
  {
    id: 8,
    name: "Coca-Cola",
    size: "1L",
    price: 150,
    category: "mixers",
    fast6: true,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCRcy3feQvg-WQja0f5WO9bhjfIwFohZeXXBjmKroWAsqH62OZ4eucQ-fWoguJBP5KDnGgzjSaAyGdkhVtPug26uTuWIEw2ZqkFTvGeLKQ9pM4p-hzM_NCaUR4caG2RqrjHJI5O8P7J76iLGK-LUciSTCSygMJtrS547puVLPsmm7ncD9ekQt9YqAnUXE80oVsIKevepNvtubN1Sxtv3XoI1yDT7Dg3FEcjGZozWKpPabYTAaWZh-EJ",
  },
];

export const NEIGHBORHOODS = [
  "Kilimani",
  "Westlands",
  "Lavington",
  "Karen",
];
