const ZONE_MAP = {
  ngong_road_price: {
    name: 'Ngong Road',
    zonePrice: 300,
    locations: [
      { name: 'Yaya, Kilimani', keywords: ['kilimani', 'yaya'], price: 100 },
      { name: 'Karen', keywords: ['karen', 'karen hills', 'karen road', 'hardy'], price: 200 },
      { name: 'Ngong Town', keywords: ['ngong', 'ngong road', 'ngong rd'], price: 250 },
      { name: 'Runda', keywords: ['runda'], price: 300 },
      { name: 'Muthaiga', keywords: ['muthaiga'], price: 250 },
      { name: 'Dagoretti', keywords: ['dagoretti'], price: 150 },
      { name: 'Lenana', keywords: ['lenana', 'kijabe'], price: 150 },
      { name: 'Bomas', keywords: ['bomas', 'raida'], price: 150 },
      { name: 'Starehe', keywords: ['starehe', 'mugumo', 'laris'], price: 100 },
      { name: 'Kenyatta', keywords: ['kenyatta'], price: 100 },
    ],
  },
  langata_price: {
    name: "Lang'ata",
    zonePrice: 300,
    locations: [
      { name: "Lang'ata Town", keywords: ['langata', "lang'ata"], price: 100 },
      { name: 'Ofafa', keywords: ['ofafa'], price: 100 },
      { name: 'Naguru', keywords: ['naguru'], price: 150 },
      { name: 'Spring Valley', keywords: ['spring valley'], price: 200 },
      { name: 'Gigiri', keywords: ['gigiri', 'riara'], price: 250 },
      { name: 'Unga', keywords: ['unga', 'mua'], price: 100 },
      { name: 'Imara', keywords: ['imara'], price: 150 },
    ],
  },
  mombasa_road_price: {
    name: 'Mombasa Road',
    zonePrice: 300,
    locations: [
      { name: 'South B', keywords: ['south b', 'southb'], price: 100 },
      { name: 'South C', keywords: ['south c', 'southc'], price: 100 },
      { name: 'Industrial Area', keywords: ['industrial'], price: 100 },
      { name: 'Nyayo', keywords: ['nyayo', 'highrise'], price: 100 },
      { name: 'Syokimau', keywords: ['syokimau'], price: 200 },
      { name: 'Kitengela', keywords: ['kitengela'], price: 250 },
      { name: 'Athi River', keywords: ['athi river'], price: 250 },
      { name: 'Utawala', keywords: ['utawala'], price: 150 },
    ],
  },
  waiyaki_way_price: {
    name: 'Waiyaki Way',
    zonePrice: 300,
    locations: [
      { name: 'Westlands', keywords: ['westlands', 'westie'], price: 100 },
      { name: 'Parklands', keywords: ['parklands'], price: 100 },
      { name: 'Lavington', keywords: ['lavington'], price: 150 },
      { name: 'Kileleshwa', keywords: ['kileleshwa'], price: 150 },
      { name: 'Spring Valley', keywords: ['spring valley'], price: 200 },
      { name: 'Loresho', keywords: ['loresho'], price: 200 },
      { name: 'Kitisuru', keywords: ['kitisuru'], price: 250 },
      { name: 'Kangemi', keywords: ['kangemi'], price: 100 },
      { name: 'Mountain View', keywords: ['mountain view'], price: 150 },
    ],
  },
  limuru_road_price: {
    name: 'Limuru Road',
    zonePrice: 300,
    locations: [
      { name: 'Kikuyu', keywords: ['kikuyu'], price: 200 },
      { name: 'Limuru Town', keywords: ['limuru', 'limuru road', 'limuru rd'], price: 250 },
      { name: 'Kiambaa', keywords: ['kiambaa'], price: 200 },
      { name: 'Kabete', keywords: ['kabete'], price: 200 },
      { name: 'Uthiru', keywords: ['uthiru', 'u.thiru'], price: 150 },
      { name: 'Karuri', keywords: ['karuri'], price: 200 },
      { name: 'Tigoni', keywords: ['tigoni'], price: 250 },
    ],
  },
  kiambu_road_price: {
    name: 'Kiambu Road',
    zonePrice: 300,
    locations: [
      { name: 'Kasarani', keywords: ['kasarani'], price: 100 },
      { name: 'Mwiki', keywords: ['mwiki'], price: 100 },
      { name: 'Ruiru', keywords: ['ruiru'], price: 150 },
      { name: 'Juja', keywords: ['juja'], price: 200 },
      { name: 'Kiambu Town', keywords: ['kiambu', 'kiambu road', 'kiambu rd'], price: 250 },
      { name: 'Ruaka', keywords: ['ruaka'], price: 150 },
      { name: 'Two Rivers', keywords: ['two rivers', 'trm'], price: 100 },
    ],
  },
  thika_road_price: {
    name: 'Thika Road',
    zonePrice: 300,
    locations: [
      { name: 'Roysambu', keywords: ['roysambu'], price: 100 },
      { name: 'Kahawa', keywords: ['kahawa', 'kahawa west', 'kahawa sukari'], price: 100 },
      { name: 'Zimmerman', keywords: ['zimmerman'], price: 100 },
      { name: 'Garden City', keywords: ['garden city'], price: 100 },
      { name: 'Mirema', keywords: ['mirema'], price: 100 },
      { name: 'Thika Town', keywords: ['thika', 'thika road', 'thika rd'], price: 250 },
    ],
  },
  jogoo_road_price: {
    name: 'Jogoo Road',
    zonePrice: 300,
    locations: [
      { name: 'Buruburu', keywords: ['buruburu'], price: 100 },
      { name: 'Donholm', keywords: ['donholm'], price: 100 },
      { name: 'Pipeline', keywords: ['pipeline'], price: 100 },
      { name: 'Kayole', keywords: ['kayole'], price: 100 },
      { name: 'Kariobangi', keywords: ['kariobangi'], price: 100 },
      { name: 'Dandora', keywords: ['dandora'], price: 100 },
      { name: 'Eastlands', keywords: ['eastlands', 'hamza', 'meanwood'], price: 100 },
    ],
  },
};

module.exports = { ZONE_MAP };
