/**
 * Static fallback delivery-zone rate card.
 *
 * Used only when there is no synced WooCommerce zone data (see
 * lib/shipping.js#getZoneCatalog). Transcribed from the "Liquor End Palace x
 * Happy Hour" delivery rate card (same-day door-step delivery across
 * Nairobi) — this is the actual manually-priced table the business uses, not
 * a placeholder. Keep it in sync with that source; it is also editable from
 * the admin Delivery Zones page, which writes over these defaults once an
 * admin has made any change.
 */
const ZONE_MAP = {
  langata_price: {
    name: "Lang'ata",
    zonePrice: 300,
    locations: [
      { name: 'Nairobi West', keywords: ['nairobi west'], price: 300 },
      { name: 'Madaraka', keywords: ['madaraka'], price: 300 },
      { name: 'T Mall', keywords: ['t mall', 'tmall'], price: 300 },
      { name: 'Qwetu Mbagathi', keywords: ['qwetu mbagathi', 'qwetu'], price: 300 },
      { name: 'Kenyatta Market', keywords: ['kenyatta market'], price: 300 },
      { name: 'Mbagathi Hospital', keywords: ['mbagathi hospital', 'mbagathi'], price: 300 },
      { name: 'Golf Course Estate', keywords: ['golf course estate', 'golf course'], price: 300 },
      { name: 'Kemri', keywords: ['kemri'], price: 300 },
      { name: 'Highview Estate', keywords: ['highview estate', 'highview'], price: 300 },
      { name: 'Wilson Airport', keywords: ['wilson airport', 'wilson'], price: 300 },
      { name: '1824', keywords: ['1824'], price: 300 },
      { name: 'Freedom Heights', keywords: ['freedom heights'], price: 300 },
      { name: 'Jupiter Guest House', keywords: ['jupiter guest house', 'jupiter'], price: 300 },
      { name: 'Jamhuri Heights', keywords: ['jamhuri heights', 'jamhuri'], price: 300 },
      { name: 'Carnivore Stage', keywords: ['carnivore stage', 'carnivore'], price: 300 },
      { name: 'Tamrind Tree', keywords: ['tamrind tree', 'tamarind tree', 'tamarind'], price: 300 },
      { name: 'Westpark Police Canteen', keywords: ['westpark police canteen', 'westpark'], price: 300 },
      { name: 'Phenom Estate', keywords: ['phenom estate', 'phenom'], price: 300 },
      { name: "Jonathan Nge'no Estate", keywords: ['jonathan ngeno estate', 'jonathan ngeno'], price: 300 },
      { name: "NHC Lang'ata", keywords: ['nhc langata', 'nhc'], price: 300 },
      { name: "Lang'ata Estate", keywords: ['langata estate'], price: 300 },
      { name: 'Bomas', keywords: ['bomas'], price: 450 },
      { name: 'Bogani Road', keywords: ['bogani road', 'bogani'], price: 550 },
    ],
  },
  waiyaki_way_price: {
    name: 'Waiyaki Way',
    zonePrice: 300,
    locations: [
      { name: 'Museum Hill', keywords: ['museum hill', 'museum'], price: 250 },
      { name: 'Chiromo upto Mortuary', keywords: ['chiromo', 'chiromo mortuary'], price: 250 },
      { name: 'Riverside Drive', keywords: ['riverside drive', 'riverside'], price: 300 },
      { name: 'The Mall Westlands', keywords: ['the mall westlands', 'mall westlands', 'westlands mall'], price: 300 },
      { name: 'Sarit Centre', keywords: ['sarit centre', 'sarit center', 'sarit'], price: 300 },
      { name: 'Safaricom HQ', keywords: ['safaricom hq', 'safaricom headquarters'], price: 300 },
      { name: 'Safaricom HQ3', keywords: ['safaricom hq3', 'hq3'], price: 300 },
      { name: 'Rhapta Road', keywords: ['rhapta road', 'rhapta'], price: 300 },
      { name: 'Muthangari Drive', keywords: ['muthangari drive', 'muthangari'], price: 300 },
      { name: 'ABC Place', keywords: ['abc place'], price: 300 },
      { name: 'Brookside Groove', keywords: ['brookside groove', 'brookside'], price: 300 },
      { name: 'Deloitte', keywords: ['deloitte'], price: 300 },
      { name: 'Kianda School', keywords: ['kianda school', 'kianda'], price: 300 },
      { name: 'Loresho Mountain View', keywords: ['loresho mountain view', 'loresho'], price: 400 },
      { name: 'ILRI', keywords: ['ilri'], price: 400 },
      { name: 'Uthiru', keywords: ['uthiru'], price: 500 },
      { name: 'Kinoo', keywords: ['kinoo'], price: 500 },
      { name: 'Kinoo Estates', keywords: ['kinoo estates'], price: 500 },
    ],
  },
  mombasa_road_price: {
    name: 'Mombasa Road',
    zonePrice: 300,
    locations: [
      { name: 'South C', keywords: ['south c'], price: 300 },
      { name: 'West Suites', keywords: ['west suites'], price: 300 },
      { name: 'Kenya Water Institutes', keywords: ['kenya water institutes', 'kenya water institute'], price: 300 },
      { name: 'Capital Centre', keywords: ['capital centre', 'capital center'], price: 300 },
      { name: 'Akira Estate', keywords: ['akira estate', 'akira'], price: 300 },
      { name: 'Mbugani Estate', keywords: ['mbugani estate', 'mbugani'], price: 300 },
      { name: 'Mugoya Estate', keywords: ['mugoya estate', 'mugoya'], price: 300 },
      { name: 'Five Star Estate', keywords: ['five star estate', 'five star'], price: 300 },
      { name: 'Ruby Estate', keywords: ['ruby estate', 'ruby'], price: 300 },
      { name: 'Next Gen', keywords: ['next gen'], price: 300 },
      { name: 'General Motors (GM)', keywords: ['general motors', 'gm'], price: 300 },
      { name: 'South B Centre', keywords: ['south b centre', 'south b center'], price: 300 },
      { name: 'Sanasana', keywords: ['sanasana'], price: 300 },
      { name: 'Mater Hospital', keywords: ['mater hospital', 'mater'], price: 300 },
      { name: 'Dt Dobie', keywords: ['dt dobie', 'dobie'], price: 300 },
      { name: 'Industrial Police Post', keywords: ['industrial police post', 'industrial area police'], price: 350 },
      { name: 'South B Hazina Estate', keywords: ['south b hazina estate', 'hazina estate', 'hazina'], price: 300 },
      { name: 'South B Balozi', keywords: ['south b balozi', 'balozi'], price: 300 },
      { name: 'Mukuru Kayaba', keywords: ['mukuru kayaba', 'mukuru'], price: 300 },
      { name: 'Diamond Park', keywords: ['diamond park'], price: 300 },
      { name: 'Parkside Villas', keywords: ['parkside villas', 'parkside'], price: 300 },
      { name: 'Tetra Park Estate', keywords: ['tetra park estate', 'tetra park'], price: 300 },
      { name: 'Imara Daima', keywords: ['imara daima', 'imara'], price: 350 },
      { name: 'Southfield Mall', keywords: ['southfield mall', 'southfield'], price: 350 },
      { name: 'Cabanas', keywords: ['cabanas'], price: 400 },
      { name: 'Pipeline Estate', keywords: ['pipeline estate', 'pipeline'], price: 400 },
    ],
  },
  limuru_road_price: {
    name: 'Limuru Road',
    zonePrice: 450,
    locations: [
      { name: 'Parklands', keywords: ['parklands'], price: 250 },
      { name: 'Gigiri', keywords: ['gigiri'], price: 400 },
      { name: 'Ruaka Quickmart', keywords: ['ruaka quickmart', 'quickmart ruaka'], price: 500 },
      { name: 'Rosslyn', keywords: ['rosslyn'], price: 450 },
      { name: 'Ruaka Joyland', keywords: ['ruaka joyland', 'joyland'], price: 500 },
      { name: 'Ruaka View Apartments', keywords: ['ruaka view apartments', 'ruaka view'], price: 550 },
      { name: 'Cytonn Apts Ruaka', keywords: ['cytonn apts ruaka', 'cytonn'], price: 550 },
      { name: 'Lane 26 Ruaka', keywords: ['lane 26 ruaka', 'lane 26'], price: 550 },
      { name: 'Two Rivers N. Bypass', keywords: ['two rivers', 'two rivers bypass', 'northern bypass'], price: 450 },
    ],
  },
  kiambu_road_price: {
    name: 'Kiambu Road',
    zonePrice: 350,
    locations: [
      { name: 'D.C.I', keywords: ['d c i', 'dci'], price: 350 },
      { name: 'Fourways', keywords: ['fourways'], price: 300 },
      { name: 'Ridgeways', keywords: ['ridgeways'], price: 350 },
      { name: 'Thindigua', keywords: ['thindigua'], price: 400 },
      { name: 'Edenville', keywords: ['edenville'], price: 450 },
      { name: 'Kiambu', keywords: ['kiambu'], price: 550 },
      { name: 'Muthaiga', keywords: ['muthaiga'], price: 350 },
    ],
  },
  ngong_road_price: {
    name: 'Ngong Road',
    zonePrice: 200,
    locations: [
      { name: 'Coptic Hospital', keywords: ['coptic hospital', 'coptic'], price: 100 },
      { name: 'D.O.D', keywords: ['d o d', 'dod'], price: 100 },
      { name: 'Hurlingham', keywords: ['hurlingham'], price: 100 },
      { name: 'State House', keywords: ['state house'], price: 100 },
      { name: 'Yaya Center', keywords: ['yaya center', 'yaya centre', 'yaya'], price: 100 },
      { name: 'Prestige', keywords: ['prestige'], price: 150 },
      { name: 'Dennis Pritt', keywords: ['dennis pritt'], price: 100 },
      { name: 'Kileleshwa', keywords: ['kileleshwa'], price: 150 },
      { name: 'Valley Arcade Mall', keywords: ['valley arcade mall', 'valley arcade'], price: 150 },
      { name: 'Junction', keywords: ['the junction', 'junction mall', 'junction'], price: 200 },
      { name: 'Lavington Muthangari', keywords: ['lavington muthangari'], price: 200 },
      { name: 'Lavington Magetaa Road', keywords: ['lavington magetaa road', 'magetaa road', 'magetaa'], price: 200 },
      { name: 'Lavington Hendred Road', keywords: ['lavington hendred road', 'hendred road', 'hendred'], price: 200 },
      { name: 'Mbaazi Avenue', keywords: ['mbaazi avenue', 'mbaazi'], price: 200 },
      { name: 'Hatheru Road', keywords: ['hatheru road', 'hatheru'], price: 200 },
      { name: 'Amboseli Road', keywords: ['amboseli road', 'amboseli'], price: 200 },
      { name: 'Njumbi Road', keywords: ['njumbi road', 'njumbi'], price: 200 },
      { name: 'Kawangware Stage', keywords: ['kawangware stage', 'kawangware'], price: 250 },
      { name: 'Kenol', keywords: ['kenol'], price: 150 },
      { name: '46 Gitanga Road', keywords: ['46 gitanga road', 'gitanga road', 'gitanga'], price: 250 },
      { name: 'Rusinga School', keywords: ['rusinga school', 'rusinga'], price: 150 },
      { name: 'Racecourse', keywords: ['racecourse'], price: 150 },
      { name: 'Lenana School', keywords: ['lenana school', 'lenana'], price: 300 },
      { name: 'Wanyee Road', keywords: ['wanyee road', 'wanyee'], price: 200 },
      { name: 'Riruta', keywords: ['riruta'], price: 250 },
      { name: 'Satelite', keywords: ['satelite', 'satellite'], price: 300 },
    ],
  },
  thika_road_price: {
    name: 'Thika Road',
    zonePrice: 350,
    locations: [
      { name: 'Garden City', keywords: ['garden city'], price: 350 },
      { name: 'TRM', keywords: ['trm'], price: 350 },
      { name: 'Roysambu', keywords: ['roysambu'], price: 350 },
      { name: 'Kahawa West', keywords: ['kahawa west'], price: 450 },
      { name: 'Kahawa Wendani', keywords: ['kahawa wendani'], price: 450 },
      { name: 'Jacaranda', keywords: ['jacaranda'], price: 550 },
      { name: 'Ruiru', keywords: ['ruiru'], price: 550 },
    ],
  },
  jogoo_road_price: {
    name: 'Jogoo Road',
    zonePrice: 350,
    locations: [
      { name: 'Buruburu', keywords: ['buruburu'], price: 350 },
      { name: 'Donholm', keywords: ['donholm'], price: 350 },
      { name: 'Umoja', keywords: ['umoja'], price: 350 },
      { name: 'Fedha', keywords: ['fedha'], price: 350 },
      { name: 'Nyayo Estate', keywords: ['nyayo estate', 'nyayo'], price: 400 },
      { name: 'Nasra', keywords: ['nasra'], price: 400 },
      { name: 'Komarocks', keywords: ['komarocks', 'komarock'], price: 400 },
    ],
  },
};

module.exports = { ZONE_MAP };
